name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install prettier
        run: |
          npm install -g prettier

      - name: Verify Go & Prettier formatting
        run: |
          make lint-check

      - name: Run tests
        run: |
          make test
